/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')();
const IndexLazyImport = createFileRoute('/')();
const CoinsCoinIdLazyImport = createFileRoute('/coins/$coinId')();

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));

const CoinsCoinIdLazyRoute = CoinsCoinIdLazyImport.update({
  path: '/coins/$coinId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/coins.$coinId.lazy').then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/about': {
      preLoaderRoute: typeof AboutLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/coins/$coinId': {
      preLoaderRoute: typeof CoinsCoinIdLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexLazyRoute, AboutLazyRoute, CoinsCoinIdLazyRoute]);

/* prettier-ignore-end */
